# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate Euclidean Distance between two vectors
#' @param x NumericVector
#' @param y NumericVector
#' @return double Euclidean distance
#' @export
euclidean_dist <- function(x, y) {
    .Call(`_lslearn_euclidean_dist`, x, y)
}

