# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' All combinations of size l from a vector
#'
#' @param x Numeric vector of values to choose from.
#' @param l Size of each combination.
#' @return A numeric matrix with `l` rows, one column per combination
#'   (delegating to R's `combn()` when there is more than one element to
#'   choose from). When `l` is 0, returns a 1x1 matrix containing `NA`,
#'   representing the (single) empty combination.
#' @details
#' Tested: 12/16/20. Confirmed: 11/23/22.
#' @noRd
combn_cpp <- function(x, l) {
    .Call(`_lslearn_combn_cpp`, x, l)
}

#' Test whether a value is present in a numeric vector
#'
#' @param x Numeric vector to search.
#' @param i Value to search for.
#' @return `TRUE` if `i` is an element of `x`, `FALSE` otherwise.
#' @details Tested: 11/23/22.
#' @noRd
isMember <- function(x, i) {
    .Call(`_lslearn_isMember`, x, i)
}

#' Partial correlation between two variables given a conditioning set
#'
#' @param C Correlation matrix of all variables under consideration.
#' @param i,j 0-based indices into `C` of the two variables being tested.
#' @param k 0-based indices into `C` of the conditioning set; may be empty.
#' @return The partial correlation between variables `i` and `j` given the
#'   variables in `k`. For an empty conditioning set this is just `C(i, j)`;
#'   for one conditioning variable it uses the closed-form recursion; for
#'   larger conditioning sets it inverts the relevant submatrix of `C`.
#' @noRd
getPartialCorrelation <- function(C, i, j, k) {
    .Call(`_lslearn_getPartialCorrelation`, C, i, j, k)
}

#' Fisher z-transformed test statistic for a partial correlation
#'
#' @param pc A partial correlation, e.g. from `getPartialCorrelation()`.
#' @param n Sample size.
#' @param k_size Size of the conditioning set used to compute `pc`.
#' @return The test statistic `sqrt(n - k_size - 3) * atanh(pc)`, which is
#'   asymptotically standard normal under the null of zero partial
#'   correlation (Kalisch and Buhlmann, 2007).
#' @noRd
fisherZ <- function(pc, n, k_size) {
    .Call(`_lslearn_fisherZ`, pc, n, k_size)
}

#' Conditional independence test for continuous data via partial correlation
#'
#' @param C Correlation matrix of all variables under consideration.
#' @param i,j 0-based indices into `C` of the two variables being tested.
#' @param k 0-based indices into `C` of the conditioning set; may be empty.
#' @param n Sample size.
#' @param signif_level Significance level of the test.
#' @return A list with `result` (`TRUE` if the null of conditional
#'   independence is not rejected, i.e. `Xi` and `Xj` are declared
#'   conditionally independent given `Xk`), `statistic` (the Fisher
#'   z-transformed test statistic), and `pval` (the corresponding two-sided
#'   p-value).
#' @noRd
condIndTest <- function(C, i, j, k, n, signif_level) {
    .Call(`_lslearn_condIndTest`, C, i, j, k, n, signif_level)
}

#' Population-level (oracle) conditional independence test via d-separation
#'
#' @param G 0/1 adjacency matrix of the true DAG.
#' @param i,j 0-based node indices to test for d-separation.
#' @param k 0-based indices of the conditioning set; may be empty.
#' @return A list with `result` (`TRUE` if `i` and `j` are d-separated by
#'   `k` in `G`, i.e. conditionally independent given a CI oracle) and
#'   `pval` (1 if d-separated, 0 otherwise), for interface consistency with
#'   `condIndTest()`.
#' @details Delegates to the R-level `my_dsep()` helper (see
#'   `R/misc-helper.R`), which in turn uses `bnlearn::dsep()`.
#' @noRd
condIndTestPop <- function(G, i, j, k) {
    .Call(`_lslearn_condIndTestPop`, G, i, j, k)
}

#' Encode each row of a discrete conditioning set as a single joint level
#'
#' @param sep_vectors A matrix whose columns are the discrete levels of each
#'   variable in a conditioning set, one row per observation.
#' @return A numeric vector with one entry per row of `sep_vectors`, giving
#'   a base-10 encoding of that row's combination of levels (treating each
#'   column as a base-10 "digit"). Two rows get the same value if and only
#'   if they have the same combination of levels, so this is used to
#'   enumerate the distinct joint strata of a (possibly multivariate)
#'   conditioning set.
#' @noRd
matrix_to_string <- function(sep_vectors) {
    .Call(`_lslearn_matrix_to_string`, sep_vectors)
}

#' G2 statistic for association between two discrete variables in one stratum
#'
#' @param A,B Numeric vectors of discrete levels for the two variables being
#'   tested, restricted to a single stratum of the conditioning set.
#' @param tot_Au_size,tot_Bu_size Total number of possible levels for `A`
#'   and `B` across *all* strata (not just this one), so the contingency
#'   table dimensions are consistent when summed across strata by
#'   `get_G2_all()`.
#' @return The G2 (likelihood-ratio chi-squared) statistic for `A` and `B`
#'   within this stratum, computed as twice the sum over observed cells of
#'   `observed * log(observed / expected)`, with zero-count cells skipped.
#' @noRd
get_G2_one <- function(A, B, tot_Au_size, tot_Bu_size) {
    .Call(`_lslearn_get_G2_one`, A, B, tot_Au_size, tot_Bu_size)
}

#' G2 statistic for association between two discrete variables given a
#' conditioning set
#'
#' @param A,B Numeric vectors of discrete levels for the two variables being
#'   tested.
#' @param S Numeric vector giving the joint level of the conditioning set
#'   for each observation, as produced by `matrix_to_string()`.
#' @return The G2 statistic for `A` and `B` given `S`, computed as the sum
#'   of the per-stratum G2 statistics (see `get_G2_one()`) over each
#'   distinct level of `S`.
#' @noRd
get_G2_all <- function(A, B, S) {
    .Call(`_lslearn_get_G2_all`, A, B, S)
}

#' Conditional independence test for discrete data via the G2 statistic
#'
#' @param df Data matrix of discrete (integer-coded) variables, one column
#'   per variable and one row per observation.
#' @param i,j 0-based column indices into `df` of the two variables being
#'   tested.
#' @param k 0-based column indices into `df` of the conditioning set.
#' @param signif_level Significance level of the test.
#' @return A list with `result` (`TRUE` if the null of conditional
#'   independence is not rejected), `statistic` (the G2 statistic from
#'   `get_G2_all()`), and `pval` (the corresponding upper-tail chi-squared
#'   p-value, using the degrees of freedom implied by the number of levels
#'   of `A`, `B`, and the conditioning set).
#' @noRd
condInttestdis <- function(df, i, j, k, signif_level) {
    .Call(`_lslearn_condInttestdis`, df, i, j, k, signif_level)
}

testArmaCor <- function(M) {
    .Call(`_lslearn_testArmaCor`, M)
}

test_union <- function(x, y) {
    .Call(`_lslearn_test_union`, x, y)
}

test_sort <- function(x) {
    .Call(`_lslearn_test_sort`, x)
}

test_fill <- function(nrow, ncol, value) {
    .Call(`_lslearn_test_fill`, nrow, ncol, value)
}

test_fill_diag <- function(x, value) {
    .Call(`_lslearn_test_fill_diag`, x, value)
}

test_create <- function(x1, x2) {
    .Call(`_lslearn_test_create`, x1, x2)
}

test_setdiff <- function(v1, v2) {
    .Call(`_lslearn_test_setdiff`, v1, v2)
}

test_intersect <- function(v1, v2) {
    .Call(`_lslearn_test_intersect`, v1, v2)
}

test_map_insert <- function(v1, v2) {
    .Call(`_lslearn_test_map_insert`, v1, v2)
}

test_map_find <- function(v1, v2, a) {
    invisible(.Call(`_lslearn_test_map_find`, v1, v2, a))
}

test_sep_arma <- function() {
    .Call(`_lslearn_test_sep_arma`)
}

test_subset_mat <- function(m, i) {
    .Call(`_lslearn_test_subset_mat`, m, i)
}

test_NumMat_value <- function(G) {
    .Call(`_lslearn_test_NumMat_value`, G)
}

test_decrement_matrix <- function(G) {
    invisible(.Call(`_lslearn_test_decrement_matrix`, G))
}

printS <- function(neighbors) {
    invisible(.Call(`_lslearn_printS`, neighbors))
}

getInitialValues <- function(neighbors, i, j) {
    .Call(`_lslearn_getInitialValues`, neighbors, i, j)
}

setListEmptySet <- function(neighbors, i, j) {
    .Call(`_lslearn_setListEmptySet`, neighbors, i, j)
}

setListEfficient <- function(neighbors, i, j, kvals) {
    .Call(`_lslearn_setListEfficient`, neighbors, i, j, kvals)
}

checkSeparationFunc <- function(neighbors, i, j, sep, val_to_check) {
    .Call(`_lslearn_checkSeparationFunc`, neighbors, i, j, sep, val_to_check)
}

checkSeparationFuncCorrected <- function(neighbors, i, j, sep, val_to_check) {
    .Call(`_lslearn_checkSeparationFuncCorrected`, neighbors, i, j, sep, val_to_check)
}

checkIsSepSetMember <- function(neighbors, i, j, sep1, sep2, val_to_check) {
    .Call(`_lslearn_checkIsSepSetMember`, neighbors, i, j, sep1, sep2, val_to_check)
}

checkPotentialVStruct <- function(neighbors, i, j, sep, k) {
    .Call(`_lslearn_checkPotentialVStruct`, neighbors, i, j, sep, k)
}

checkGetS <- function(neighbors, i, j, sep) {
    .Call(`_lslearn_checkGetS`, neighbors, i, j, sep)
}

