# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run the sample (or semi-sample) version of SNL and collect its results
#'
#' Internal building block for `snl()`; end users should call `snl()`
#' rather than this function directly.
#'
#' @param true_dag 0/1 adjacency matrix: the true DAG structure (semi-sample
#'   version) or an estimated Markov Blanket inclusion matrix (`estDAG =
#'   TRUE`).
#' @param df Data matrix (0-indexed internally).
#' @param targets,nodes_interest 0-based target and neighborhood-of-interest
#'   node indices.
#' @param names Node names.
#' @param lmax Maximum conditioning set size.
#' @param signif_level Significance level for conditional independence
#'   tests.
#' @param verbose Whether to print detailed output.
#' @param test Which conditional independence test to use.
#' @param estDAG Whether `true_dag` is an estimated Markov Blanket matrix
#'   rather than the true DAG.
#' @returns A list with the estimated graph (`G`), separating sets (`S`),
#'   test counts, node ordering, orientation rule usage, and timing
#'   information; see `snl()` for the user-facing result shape.
#' @noRd
sampleSNL <- function(true_dag, df, targets, nodes_interest, names, lmax = 3L, signif_level = 0.01, verbose = TRUE, test = "testIndFisher", estDAG = FALSE) {
    .Call(`_lslearn_sampleSNL`, true_dag, df, targets, nodes_interest, names, lmax, signif_level, verbose, test, estDAG)
}

#' Run the population (oracle) version of SNL and collect its results
#'
#' Internal building block for `snl()`; end users should call `snl()`
#' rather than this function directly.
#'
#' @inheritParams sampleSNL
#' @returns Same shape as `sampleSNL()`, minus the sample-only
#'   `algorithmTotalTime` entry.
#' @noRd
popSNL <- function(true_dag, targets, nodes_interest, names, lmax = 3L, verbose = TRUE) {
    .Call(`_lslearn_popSNL`, true_dag, targets, nodes_interest, names, lmax, verbose)
}

#' Validate that a target node is a member of the target vector
#'
#' @param targets Numeric vector of 0-based target node indices.
#' @param t The 0-based node index to validate.
#' @return Invisibly, `NULL`. Raises an error if `t` is not a member of
#'   `targets`.
#' @noRd
validateTargetSNL <- function(targets, t) {
    invisible(.Call(`_lslearn_validateTargetSNL`, targets, t))
}

#' All combinations of size l from a vector
#'
#' @param x Numeric vector of values to choose from.
#' @param l Size of each combination.
#' @return A numeric matrix with `l` rows, one column per combination
#'   (delegating to R's `combn()` when there is more than one element to
#'   choose from). When `l` is 0, returns a 1x1 matrix containing `NA`,
#'   representing the (single) empty combination.
#' @details
#' Tested: 12/16/20. Confirmed: 11/23/22.
#'
#' `l` is taken as a signed `int` (rather than `size_t`) specifically so a
#' negative value can be rejected explicitly here: converting a negative
#' double straight to `size_t` at the Rcpp boundary is implementation- and
#' version-defined (it has been observed to both wrap around to a huge
#' positive value and to clamp to 0 across different Rcpp/compiler
#' versions), so it isn't a reliable way to reject bad input.
#' @noRd
combn_cpp <- function(x, l) {
    .Call(`_lslearn_combn_cpp`, x, l)
}

#' Test whether a value is present in a numeric vector
#'
#' @param x Numeric vector to search.
#' @param i Value to search for.
#' @return `TRUE` if `i` is an element of `x`, `FALSE` otherwise.
#' @details Tested: 11/23/22.
#' @noRd
isMember <- function(x, i) {
    .Call(`_lslearn_isMember`, x, i)
}

#' Partial correlation between two variables given a conditioning set
#'
#' @param C Correlation matrix of all variables under consideration.
#' @param i,j 0-based indices into `C` of the two variables being tested.
#' @param k 0-based indices into `C` of the conditioning set; may be empty.
#' @return The partial correlation between variables `i` and `j` given the
#'   variables in `k`. For an empty conditioning set this is just `C(i, j)`;
#'   for one conditioning variable it uses the closed-form recursion; for
#'   larger conditioning sets it inverts the relevant submatrix of `C`.
#' @noRd
getPartialCorrelation <- function(C, i, j, k) {
    .Call(`_lslearn_getPartialCorrelation`, C, i, j, k)
}

#' Fisher z-transformed test statistic for a partial correlation
#'
#' @param pc A partial correlation, e.g. from `getPartialCorrelation()`.
#' @param n Sample size.
#' @param k_size Size of the conditioning set used to compute `pc`.
#' @return The test statistic `sqrt(n - k_size - 3) * atanh(pc)`, which is
#'   asymptotically standard normal under the null of zero partial
#'   correlation (Kalisch and Buhlmann, 2007).
#' @noRd
fisherZ <- function(pc, n, k_size) {
    .Call(`_lslearn_fisherZ`, pc, n, k_size)
}

#' Conditional independence test for continuous data via partial correlation
#'
#' @param C Correlation matrix of all variables under consideration.
#' @param i,j 0-based indices into `C` of the two variables being tested.
#' @param k 0-based indices into `C` of the conditioning set; may be empty.
#' @param n Sample size.
#' @param signif_level Significance level of the test.
#' @return A list with `result` (`TRUE` if the null of conditional
#'   independence is not rejected, i.e. `Xi` and `Xj` are declared
#'   conditionally independent given `Xk`), `statistic` (the Fisher
#'   z-transformed test statistic), and `pval` (the corresponding two-sided
#'   p-value).
#' @noRd
condIndTest <- function(C, i, j, k, n, signif_level) {
    .Call(`_lslearn_condIndTest`, C, i, j, k, n, signif_level)
}

#' Population-level (oracle) conditional independence test via d-separation
#'
#' @param G 0/1 adjacency matrix of the true DAG.
#' @param i,j 0-based node indices to test for d-separation.
#' @param k 0-based indices of the conditioning set; may be empty.
#' @return A list with `result` (`TRUE` if `i` and `j` are d-separated by
#'   `k` in `G`, i.e. conditionally independent given a CI oracle) and
#'   `pval` (1 if d-separated, 0 otherwise), for interface consistency with
#'   `condIndTest()`.
#' @details Delegates to the R-level `my_dsep()` helper (see
#'   `R/misc-helper.R`), which in turn uses `bnlearn::dsep()`. `my_dsep()`
#'   is internal (not exported), so it must be looked up through the
#'   package namespace rather than via a plain `Function("my_dsep")`
#'   constructor: the latter only finds it when the whole package is
#'   attached to the search path unnamespaced (e.g. under
#'   `pkgload::load_all()`), not for a normally `library()`-loaded
#'   package, where non-exported functions aren't on the search path by
#'   name.
#' @noRd
condIndTestPop <- function(G, i, j, k) {
    .Call(`_lslearn_condIndTestPop`, G, i, j, k)
}

#' Encode each row of a discrete conditioning set as a single joint level
#'
#' @param sep_vectors A matrix whose columns are the discrete levels of each
#'   variable in a conditioning set, one row per observation.
#' @return A numeric vector with one entry per row of `sep_vectors`, giving
#'   a base-10 encoding of that row's combination of levels (treating each
#'   column as a base-10 "digit"). Two rows get the same value if and only
#'   if they have the same combination of levels, so this is used to
#'   enumerate the distinct joint strata of a (possibly multivariate)
#'   conditioning set.
#' @noRd
matrix_to_string <- function(sep_vectors) {
    .Call(`_lslearn_matrix_to_string`, sep_vectors)
}

#' G2 statistic for association between two discrete variables in one stratum
#'
#' @param A,B Numeric vectors of discrete levels for the two variables being
#'   tested, restricted to a single stratum of the conditioning set.
#' @param tot_Au_size,tot_Bu_size Total number of possible levels for `A`
#'   and `B` across *all* strata (not just this one), so the contingency
#'   table dimensions are consistent when summed across strata by
#'   `get_G2_all()`.
#' @return The G2 (likelihood-ratio chi-squared) statistic for `A` and `B`
#'   within this stratum, computed as twice the sum over observed cells of
#'   `observed * log(observed / expected)`, with zero-count cells skipped.
#' @noRd
get_G2_one <- function(A, B, tot_Au_size, tot_Bu_size) {
    .Call(`_lslearn_get_G2_one`, A, B, tot_Au_size, tot_Bu_size)
}

#' G2 statistic for association between two discrete variables given a
#' conditioning set
#'
#' @param A,B Numeric vectors of discrete levels for the two variables being
#'   tested.
#' @param S Numeric vector giving the joint level of the conditioning set
#'   for each observation, as produced by `matrix_to_string()`.
#' @return The G2 statistic for `A` and `B` given `S`, computed as the sum
#'   of the per-stratum G2 statistics (see `get_G2_one()`) over each
#'   distinct level of `S`.
#' @noRd
get_G2_all <- function(A, B, S) {
    .Call(`_lslearn_get_G2_all`, A, B, S)
}

#' Conditional independence test for discrete data via the G2 statistic
#'
#' @param df Data matrix of discrete (integer-coded) variables, one column
#'   per variable and one row per observation.
#' @param i,j 0-based column indices into `df` of the two variables being
#'   tested.
#' @param k 0-based column indices into `df` of the conditioning set.
#' @param signif_level Significance level of the test.
#' @return A list with `result` (`TRUE` if the null of conditional
#'   independence is not rejected), `statistic` (the G2 statistic from
#'   `get_G2_all()`), and `pval` (the corresponding upper-tail chi-squared
#'   p-value, using the degrees of freedom implied by the number of levels
#'   of `A`, `B`, and the conditioning set).
#' @noRd
condInttestdis <- function(df, i, j, k, signif_level) {
    .Call(`_lslearn_condInttestdis`, df, i, j, k, signif_level)
}

testArmaCor <- function(M) {
    .Call(`_lslearn_testArmaCor`, M)
}

testConstructSample <- function(true_dag, df, targets, nodes_interest, names, lmax, signif_level, verbose, test, estDAG) {
    .Call(`_lslearn_testConstructSample`, true_dag, df, targets, nodes_interest, names, lmax, signif_level, verbose, test, estDAG)
}

testConstructPop <- function(true_dag, targets, nodes_interest, names, lmax, verbose) {
    .Call(`_lslearn_testConstructPop`, true_dag, targets, nodes_interest, names, lmax, verbose)
}

testCheckSeparationPop <- function(true_dag, targets, nodes_interest, names, lmax, verbose, l, i, j, kvals) {
    .Call(`_lslearn_testCheckSeparationPop`, true_dag, targets, nodes_interest, names, lmax, verbose, l, i, j, kvals)
}

testCheckSeparationSample <- function(true_dag, df, targets, nodes_interest, names, lmax, signif_level, verbose, test, estDAG, l, i, j, kvals) {
    .Call(`_lslearn_testCheckSeparationSample`, true_dag, df, targets, nodes_interest, names, lmax, signif_level, verbose, test, estDAG, l, i, j, kvals)
}

testGetVStructuresManual <- function(true_dag, targets, nodes_interest, names, lmax, verbose, custom_amat, sep_i, sep_j, sep_k) {
    .Call(`_lslearn_testGetVStructuresManual`, true_dag, targets, nodes_interest, names, lmax, verbose, custom_amat, sep_i, sep_j, sep_k)
}

testPrintElements <- function(true_dag, targets, nodes_interest, names, lmax, verbose) {
    invisible(.Call(`_lslearn_testPrintElements`, true_dag, targets, nodes_interest, names, lmax, verbose))
}

testAlgoSettersAndAccessors <- function(true_dag, targets, nodes_interest, names, lmax, verbose, new_amat, new_neighbors) {
    .Call(`_lslearn_testAlgoSettersAndAccessors`, true_dag, targets, nodes_interest, names, lmax, verbose, new_amat, new_neighbors)
}

check_amat_works <- function(nodes, node_names, adj) {
    .Call(`_lslearn_check_amat_works`, nodes, node_names, adj)
}

check_amat_works_onepar <- function(nodes) {
    .Call(`_lslearn_check_amat_works_onepar`, nodes)
}

check_names_works <- function(nodes, node_names, adj) {
    .Call(`_lslearn_check_names_works`, nodes, node_names, adj)
}

check_dag_object <- function(nodes, node_names, adj, v = FALSE) {
    .Call(`_lslearn_check_dag_object`, nodes, node_names, adj, v)
}

check_pdag_object <- function(nodes, node_names, adj, v = FALSE) {
    .Call(`_lslearn_check_pdag_object`, nodes, node_names, adj, v)
}

check_dag_object2 <- function(nodes) {
    invisible(.Call(`_lslearn_check_dag_object2`, nodes))
}

check_pdag_object2 <- function(nodes) {
    invisible(.Call(`_lslearn_check_pdag_object2`, nodes))
}

check_neighbors_retrieval <- function(nodes, node_names, adj, t, v = FALSE) {
    .Call(`_lslearn_check_neighbors_retrieval`, nodes, node_names, adj, t, v)
}

check_neighbors_retrieval_multi <- function(nodes, node_names, adj, t, v = FALSE) {
    .Call(`_lslearn_check_neighbors_retrieval_multi`, nodes, node_names, adj, t, v)
}

check_pdag_neighbors_retrieval <- function(nodes, node_names, adj, t, v = FALSE) {
    .Call(`_lslearn_check_pdag_neighbors_retrieval`, nodes, node_names, adj, t, v)
}

check_amat_retrieval <- function(nodes, node_names, adj, i, j) {
    .Call(`_lslearn_check_amat_retrieval`, nodes, node_names, adj, i, j)
}

check_amat_retrieval_function <- function(nodes, node_names, adj, i, j) {
    .Call(`_lslearn_check_amat_retrieval_function`, nodes, node_names, adj, i, j)
}

check_amat_row_retrieval <- function(nodes, node_names, adj, i) {
    .Call(`_lslearn_check_amat_row_retrieval`, nodes, node_names, adj, i)
}

check_amat_col_retrieval <- function(nodes, node_names, adj, j) {
    .Call(`_lslearn_check_amat_col_retrieval`, nodes, node_names, adj, j)
}

check_adjacent_non_adjacent <- function(nodes, node_names, adj, i) {
    .Call(`_lslearn_check_adjacent_non_adjacent`, nodes, node_names, adj, i)
}

check_non_adjacent_solo <- function(nodes, node_names, adj, i) {
    .Call(`_lslearn_check_non_adjacent_solo`, nodes, node_names, adj, i)
}

check_directed_undirected <- function(nodes, node_names, adj, i, j) {
    .Call(`_lslearn_check_directed_undirected`, nodes, node_names, adj, i, j)
}

check_sizes <- function(nodes, node_names, adj) {
    .Call(`_lslearn_check_sizes`, nodes, node_names, adj)
}

check_amat_setval <- function(nodes, node_names, adj, i, j, val) {
    .Call(`_lslearn_check_amat_setval`, nodes, node_names, adj, i, j, val)
}

check_amat_setval_function <- function(nodes, node_names, adj, i, j, val) {
    .Call(`_lslearn_check_amat_setval_function`, nodes, node_names, adj, i, j, val)
}

checkIfAdjacent <- function(nodes, node_names, adj, i, j) {
    .Call(`_lslearn_checkIfAdjacent`, nodes, node_names, adj, i, j)
}

checkEmptyGraph <- function(p) {
    .Call(`_lslearn_checkEmptyGraph`, p)
}

checkAcyclicity <- function(nodes, node_names, adj) {
    .Call(`_lslearn_checkAcyclicity`, nodes, node_names, adj)
}

checkIsAncestor <- function(nodes, node_names, adj, desc, anc, verbose = FALSE) {
    .Call(`_lslearn_checkIsAncestor`, nodes, node_names, adj, desc, anc, verbose)
}

checkInNeighborhood <- function(nodes, node_names, adj, i, j, verbose = FALSE) {
    .Call(`_lslearn_checkInNeighborhood`, nodes, node_names, adj, i, j, verbose)
}

check_pdag_inNeighborhood <- function(nodes, node_names, adj, i, j, verbose = FALSE) {
    .Call(`_lslearn_check_pdag_inNeighborhood`, nodes, node_names, adj, i, j, verbose)
}

check_set_amat <- function(nodes, node_names, adj) {
    .Call(`_lslearn_check_set_amat`, nodes, node_names, adj)
}

check_disc_path <- function(nodes, node_names, adj, c, d, e) {
    .Call(`_lslearn_check_disc_path`, nodes, node_names, adj, c, d, e)
}

check_upd_path <- function(nodes, node_names, adj, a, b, e) {
    .Call(`_lslearn_check_upd_path`, nodes, node_names, adj, a, b, e)
}

test_checkWronglyCovered <- function(nodes, node_names, adj, p) {
    invisible(.Call(`_lslearn_test_checkWronglyCovered`, nodes, node_names, adj, p))
}

checkNeighborhoodId <- function(nodes, node_names, adj, i, verbose = FALSE) {
    .Call(`_lslearn_checkNeighborhoodId`, nodes, node_names, adj, i, verbose)
}

testInitializeMBList <- function(nodes, mb_mat) {
    invisible(.Call(`_lslearn_testInitializeMBList`, nodes, mb_mat))
}

testInitializeMBListPop <- function(nodes, amat) {
    invisible(.Call(`_lslearn_testInitializeMBListPop`, nodes, amat))
}

testAccessMB <- function(nodes, mb_mat, i) {
    .Call(`_lslearn_testAccessMB`, nodes, mb_mat, i)
}

testAccessMultipleMB <- function(nodes, mb_mat, v, include_targets = FALSE, exclude_targets = FALSE, verbose = FALSE) {
    .Call(`_lslearn_testAccessMultipleMB`, nodes, mb_mat, v, include_targets, exclude_targets, verbose)
}

testIsMBMember <- function(nodes, mb_mat, target, i) {
    .Call(`_lslearn_testIsMBMember`, nodes, mb_mat, target, i)
}

testSilencer <- function(nodes, mb_mat, target, i) {
    invisible(.Call(`_lslearn_testSilencer`, nodes, mb_mat, target, i))
}

test_union <- function(x, y) {
    .Call(`_lslearn_test_union`, x, y)
}

test_sort <- function(x) {
    .Call(`_lslearn_test_sort`, x)
}

test_fill <- function(nrow, ncol, value) {
    .Call(`_lslearn_test_fill`, nrow, ncol, value)
}

test_fill_diag <- function(x, value) {
    .Call(`_lslearn_test_fill_diag`, x, value)
}

test_create <- function(x1, x2) {
    .Call(`_lslearn_test_create`, x1, x2)
}

test_setdiff <- function(v1, v2) {
    .Call(`_lslearn_test_setdiff`, v1, v2)
}

test_intersect <- function(v1, v2) {
    .Call(`_lslearn_test_intersect`, v1, v2)
}

test_map_insert <- function(v1, v2) {
    .Call(`_lslearn_test_map_insert`, v1, v2)
}

test_map_find <- function(v1, v2, a) {
    invisible(.Call(`_lslearn_test_map_find`, v1, v2, a))
}

test_sep_arma <- function() {
    .Call(`_lslearn_test_sep_arma`)
}

test_subset_mat <- function(m, i) {
    .Call(`_lslearn_test_subset_mat`, m, i)
}

test_NumMat_value <- function(G) {
    .Call(`_lslearn_test_NumMat_value`, G)
}

test_decrement_matrix <- function(G) {
    invisible(.Call(`_lslearn_test_decrement_matrix`, G))
}

printS <- function(neighbors) {
    invisible(.Call(`_lslearn_printS`, neighbors))
}

getInitialValues <- function(neighbors, i, j) {
    .Call(`_lslearn_getInitialValues`, neighbors, i, j)
}

setListEmptySet <- function(neighbors, i, j) {
    .Call(`_lslearn_setListEmptySet`, neighbors, i, j)
}

setListEfficient <- function(neighbors, i, j, kvals) {
    .Call(`_lslearn_setListEfficient`, neighbors, i, j, kvals)
}

checkSeparationFunc <- function(neighbors, i, j, sep, val_to_check) {
    .Call(`_lslearn_checkSeparationFunc`, neighbors, i, j, sep, val_to_check)
}

checkSeparationFuncCorrected <- function(neighbors, i, j, sep, val_to_check) {
    .Call(`_lslearn_checkSeparationFuncCorrected`, neighbors, i, j, sep, val_to_check)
}

checkIsSepSetMember <- function(neighbors, i, j, sep1, sep2, val_to_check) {
    .Call(`_lslearn_checkIsSepSetMember`, neighbors, i, j, sep1, sep2, val_to_check)
}

checkPotentialVStruct <- function(neighbors, i, j, sep, k) {
    .Call(`_lslearn_checkPotentialVStruct`, neighbors, i, j, sep, k)
}

checkGetS <- function(neighbors, i, j, sep) {
    .Call(`_lslearn_checkGetS`, neighbors, i, j, sep)
}

checkInitializeSNL <- function(td, df, t, nodes_interest, names) {
    .Call(`_lslearn_checkInitializeSNL`, td, df, t, nodes_interest, names)
}

checkGetTargetSkel <- function(td, df, t, nodes_interest, names) {
    .Call(`_lslearn_checkGetTargetSkel`, td, df, t, nodes_interest, names)
}

checkGetVStructures <- function(td, df, t, nodes_interest, names) {
    .Call(`_lslearn_checkGetVStructures`, td, df, t, nodes_interest, names)
}

checkInitializeSNLPop <- function(td, t, nodes_interest, names) {
    .Call(`_lslearn_checkInitializeSNLPop`, td, t, nodes_interest, names)
}

checkGetTargetSkelPop <- function(td, t, nodes_interest, names) {
    .Call(`_lslearn_checkGetTargetSkelPop`, td, t, nodes_interest, names)
}

checkGetVStructuresPop <- function(td, t, nodes_interest, names) {
    .Call(`_lslearn_checkGetVStructuresPop`, td, t, nodes_interest, names)
}

checkRule1 <- function(td, test_mat, t, nodes_interest, names) {
    .Call(`_lslearn_checkRule1`, td, test_mat, t, nodes_interest, names)
}

checkRule2 <- function(td, test_mat, t, nodes_interest, names) {
    .Call(`_lslearn_checkRule2`, td, test_mat, t, nodes_interest, names)
}

checkRule3 <- function(td, test_mat, t, nodes_interest, names) {
    .Call(`_lslearn_checkRule3`, td, test_mat, t, nodes_interest, names)
}

checkRule4 <- function(td, test_mat, t, nodes_interest, names) {
    .Call(`_lslearn_checkRule4`, td, test_mat, t, nodes_interest, names)
}

checkSNLRules <- function(td, test_mat, t, nodes_interest, names) {
    .Call(`_lslearn_checkSNLRules`, td, test_mat, t, nodes_interest, names)
}

checkSNL <- function(td, df, t, nodes_interest, names) {
    .Call(`_lslearn_checkSNL`, td, df, t, nodes_interest, names)
}

checkSNLRun <- function(td, df, t, nodes_interest, names) {
    .Call(`_lslearn_checkSNLRun`, td, df, t, nodes_interest, names)
}

checkSNLPop <- function(td, t, nodes_interest, names) {
    .Call(`_lslearn_checkSNLPop`, td, t, nodes_interest, names)
}

